[package]
name = "redissocket"
version = "0.1.0"
authors = ["Andreas Monitzer <andreas@monitzer.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
tokio = {version = "0.1", features = ["async-await-preview"]}
tokio-io = "0.1"
